### ISSUE TITLE
Upgrading to v3 - How to implement rate limiting with slow down?

### ISSUE THREAD

**Issue by mjgs** [nfriedly/express-rate-limit#101]
I currently use v2.14.2 to rate limit with a slow down after a few tries on some routes in my app, and I am upgrading to the latest version. 

I have read the [v3 goals](https://github.com/nfriedly/express-rate-limit/issues/46), and noticed there are relevant [v3 breaking changes](https://github.com/nfriedly/express-rate-limit#v3-changes). Is the recommended implementation to use both a rate limiter and a speed limiter (using [express-slow-down](https://github.com/nfriedly/express-slow-down)) on the same route?

Also is there a reason express-slow-down does not have a feature similar to express-rate-limit's [headers feature](https://github.com/nfriedly/express-rate-limit#headers)?

**Comment by nfriedly** [comment]
Hey, sorry I missed this.

Yes, I would recommend using both. When using both, express-rate-limit will set the headers

**Comment by nfriedly** [comment]
I'm not sure. What headers would you expect beyond those?

**Comment by nfriedly** [comment]
Hey, I thought about this a bit, and I don't think that it necessarily makes sense to add the headers to the library directly. 

But I did extend the [`req.slowDown`](https://github.com/nfriedly/express-slow-down#reqslowdown) field to make it easier to do it your self.  With the just-published express-slow-down v1.1.1 you can do something like this:

```
function addSlowDownHeaders(req, res, next) {
  if (req.slowDown) {
    res.setHeader("X-SlowDown-Delay", req.slowDown.delay);
    if (req.slowDown.resetTime) { // resetTime may be undefined, it depends on the store used
      res.setHeader("X-SlowDown-Removed-In", Math.ceil( (req.slowDown.resetTime - Date.now()) / 1000); // timestamp convert to seconds
    }
  }
}

// and then use addSlowDownHead after slowDown
// so, either
app.use(slowDown);
app.use(addSlowDownHeaders);
// OR
app.get('/whatever', slowDown, addSlowDownHeaders);
```

(I didn't test this, but it should give you the general idea even if it's not quite spot on.)

**Comment by mjgs** [comment]
Well that’s something thanks. Could you expand on your reasoning for not adding the headers to the library? Just want to be sure the code I’m writing isn’t non standard. Are there any plans to remove the headers functionality from the express-rate-limit library?

**Comment by nfriedly** [comment]
Well, there aren't any standard headers that I'm aware of for slowing down responses. Anything we add would be completely made up. 

Also, I envisioned it as completely invisible to the end user unless they're breaking out a stopwatch. Basically it just mimics an overloaded server of the user starts to get abusive. So adding headers to declare what's happening kind of goes against the grain.

It's also meant to be more human-friendly because it never stops working as long as the user has sufficient patience.

Rate Limiting, on the other hand, does have (semi-)standard headers and is often a  documented and declaired part of an API. 

There are API clients that can automatically recognize and honor rate-limit headers and status codes. So, while its less human-friendly, it's more software-friendly.

So, the headers will stay in expresa-rate-limit. But at this time, I don't think it makes sense to add any headers to express-slow-down.

**Comment by mjgs** [comment]
Thanks I think your reasoning makes sense, it's good to know the reason for the slight inconsistency between the two library implementations.
