### ISSUE TITLE
Is it possible to apply limits to authenticated users and unauthenticated users?

### ISSUE THREAD

**Issue by alexllao** [nfriedly/express-rate-limit#126]
Is it possible to apply diferent limits to authenticated users and unauthenticated users?

For example, if a user is authenticated, the limit is 100 requests per hour and otherwise there are only 10 (anonymous user).

Thnks!

**Comment by nfriedly** [comment]
Yes, instead of setting the `max` option to a number, make it a function. It will be passed the `req` and `res` objects. You can then inspect them and return a different number depending on the user.  (You may also return a promise that resolves to a number if you need to do something asynchronous.)

**Comment by alexllao** [comment]
Thnks a lot!

**Comment by alexllao** [comment]
Hi! I just did it but it gives an error.

max: (req, res) => {
        return new Promise(function (resolve, reject) {
            resolve(10)  // For testing only;
        });
},

And return this error: UnhandledPromiseRejectionWarning: Error: Can't set headers after they are sent.

nhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of
an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25460) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that
are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by nfriedly** [comment]
Oh, that's not good. Do you think you can make a test that reproduces the error? 

You can base it off of this one: https://github.com/nfriedly/express-rate-limit/blob/master/test/express-rate-limit-test.js#L534

**Comment by alexllao** [comment]
The problem is that when using a middleware for user authentication using Tokens I leave the user object in req.user, but it is not accessible from

  max: (req, res) => {
         if (! req.user) {
             return process.env.API_LIMITER_CONNECTIONS;
         } else {
             if (req.user.premium) {
                 return process.env.API_REGISTERED_USER_LIMITER_CONNECTIONS;
             } else {
                 return process.env.API_LIMITER_CONNECTIONS;
             }
         }
     },

I do not know if I explain.

**Comment by nfriedly** [comment]
Aah. Could you switch the order of the middleware so that the one that authenticate the user runs before the rate limiter?

**Comment by alexllao** [comment]
Yes, that's what I just did. At the moment I have it working although I want to make some more variations. Thanks for everything.

**Comment by ambroiseRabier** [comment]
For anyone coming from the search engine: 
I was looking for limiting rate only for authenticated users, similar issue to OP. Using this library with NestJS, it doesn't seem I can change the order of middleware so that NestJS can process the request and feed it back to rateLimit.
It also doesn't seem to be a good pratice -> https://softwareengineering.stackexchange.com/questions/384494/rate-limiting-un-authenticated-requests
