### ISSUE TITLE
Can the configuration be changed on a running instance?

### ISSUE THREAD

**Issue by ADumaine** [nfriedly/express-rate-limit#163]
When using redis as a store, is it possible to change the windowMs from 10000 to 20000 or change the max without restarting the application or express?

```
const apiLimiter = rateLimit({
    store: new RedisStoreRateLimit({ client: ratelimitClientAPI }),
    windowMs: config.ratelimit.api.windowMs,
    max: config.ratelimit.api.max,
    message: {
      status: 429,
      error: 'rate limit',
      message: `Too many requests. Limit to max ${config.ratelimit.api.max} per ${config.ratelimit.api.windowMs / 1000} seconds`
    },
    headers: true,
  });

  app.use('/api/', apiLimiter);

```

**Comment by okv** [comment]
It's possible for [max](https://github.com/nfriedly/express-rate-limit/tree/52f40cc640806cd8c3130c6c1f04458980d0a60e#max) since it can be function.

**Comment by nfriedly** [comment]
Yes, sorry, I thought I had already replied with something along the lines of what @okv said.

`max` can be a function that returns a number, allowing you to change it at runtime or even have a different limit for different visitors. 

`windowMs` cannot be changed at runtime due to the way the MemoryStore is implemented, although I suppose it's feasible for other stores to implement a way to change it.
