### ISSUE TITLE
Friendly Question, I hope you don't mind

### ISSUE THREAD

**Issue by antidoxable** [nfriedly/express-rate-limit#182]
Hello nfriedly, 
I am small coder and recently I have been wanting to use your package but it was lacking a feature I required, however I have took a copy of your version and modified it with giving credits yourself as the Original Developer along with my name to this NPM/Source.

If you wish to check it out it is uploaded here: [Express Custom Limiter](https://github.com/Mr-Cerberus/express-custom-limiter) 
If you feel free to add the feature I added in my version into your's I would be happy to use your version as it would be greatly more updated than my version,

The following modification is:
```js
 handler: function(req, res /*, next*/) {
        return res.status(options.statusCode).render(options.limiterPage,{
          result: "RATELIMITED",
          message: options.message,
        });
```

**Comment by nfriedly** [comment]
Hi @Mr-Cerberus!

I'm happy that you found the library useful and that you're making it work for you, and I'd be willing to consider adding built-in support for rendering a template. 

That said, I have a few notes/requirements:

1) You can configure a custom handler function without changing the source of express-rate-limit, so a new library isn't really necessary. Here's an example that might work for you:

```js
const rateLimit = require("express-rate-limit");

const limiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes 
  max: 100, // limit each IP to 100 requests per windowMs
  // custom handler function that renders a template
  handler: function(req, res) {
    return res.status(429).render('limit-page.html', {
      result: "RATELIMITED", 
      message: "Too many requests, please try again later",
  },
});

// apply to all requestsapp.use(limiter);
```

2) The [existing license file](https://github.com/nfriedly/express-rate-limit/blob/master/LICENSE) grants you a lot of permissions, but one requirement it has is that you keep it with your copy of the code. You can add the GPL license for your changes, but my MIT license must remain with the code, and you should make it clear which changes are yours.

3) Normally, when you want to modify some one else's code on github, you'd use the fork button: 

<img width="1171" alt="Screen Shot 2020-04-06 at 11" src="https://user-images.githubusercontent.com/114976/78578514-a496d100-77fd-11ea-94b4-5df5ba0dda7d.png">

This causes github to make a full copy of my code (including the license) and keep all of the history so that it's easy to tell what was my original code and what was your changes. That makes point 2 much easier. It also makes it easy for me to incoporate your changes back into my copy.
