### ISSUE TITLE
Modify rate limiting for special routes

### ISSUE THREAD

**Issue by rekire** [nfriedly/express-rate-limit#186]
I setup my rate limiting very restrictive, however for a special route I need higher quotas. For now I excluded with skip that special route, but that is not a good option. It would be nice if there would be a build in solution to make a route more or less restrictive.

**Comment by nfriedly** [comment]
You can have a second rate-limiter that applies to only that special route. 

If it uses the default memory store, it won't share any state with the first instance. If you're using a different store, you'll need the second instance to be configured with a different prefix or collection.

**Comment by crrmacarse** [comment]
Hi @nfriedly,

Is this the right implementation?

```
app.use(
  rateLimit({
    windowMs: RATE_LIMIT_WINDOW_MS, // 15 minutes
    max: RATE_LIMIT_MAX, // limit each IP to 100 requests per windowMs
  }),
);

/** Disable rateLimit on slack routes */
app.use('/slack/', rateLimit({ max: 0 }));
```

Or am I missing something?

**Comment by nfriedly** [comment]
Sorry I wasn't clear, but no, with your example you have two rate limiters on the `/slack/` route: the original one and the max: 0 one.

Instead of `app.use(rateLimit(...))`, you could do `app.use('/route1', rateLimit(...))`, although if you're trying to do every route except one, the `skip` config option might be a better choice:

```js
app.use(
  rateLimit({
    windowMs: RATE_LIMIT_WINDOW_MS, // 15 minutes
    max: RATE_LIMIT_MAX, // limit each IP to 100 requests per windowMs
    skip: (req, res) => req.path.startsWith('/slack/'), // skip is true for slack, false for all else
  }),
);
```

I didn't test that but it should get you the right idea.
