### ISSUE TITLE
MemoryStore resetAll clears keys not meant to be cleared

### ISSUE THREAD

**Issue by jsanta** [nfriedly/express-rate-limit#194]
Let's suppose the following scenario:

- Rate limit timeout: 3 minutes. As I understand resetAll from MemoryStore would be called every 3 minutes and clear **every** key.
- Max requests: lets say 5
- t0: Some user starts making requests, on request 6 the server answers with a 429 status. Must retry after 3 minutes.
- t1: Some other user starts making requests. On minute 2:59s (since t0) the user  makes a 6th request , a 429 status is received and must retry after 3 more minutes (counting since t1)
- t1+1s: 3 minutes passed since t0, so interval calls a resetAll. The key for t1 is cleared as well. t1 was not meant to be cleared on 3 minutes past t0, but on 3 minutes past t1.

Perhaps storing an object that includes the count and the lastDate, and on the resetAll clearing only keys which age (now-lastDate) is older than windowMs.

Best regards from Chile, and stay safe,
Jose Ignacio

**Comment by nfriedly** [comment]
Hi @jsanta,

The current behavior is intentional. It originally worked the way you suggest, but I felt that it wasn't worth the extra memory and compute time. It doesn't make any difference to a normal user. And, for an abusive user, it only affects their very first cycle. After that they're stuck with the same limits either way.

However, if you do want more precise tracking, I believe all of the third party stores use a per-user time window.

**Comment by jsanta** [comment]
Hi @nfriedly .
Thanks for your answer and clarifications. Other stores were not an option for our use case, no redis, mongo nor memcache are considered in our architecture.

I'm currently working on a custom store that uses Maps instead of Objects, for performance, and  that implements the logic I mentioned. Haven't  published it yet, but  will notify you when I do.

**Comment by nfriedly** [comment]
The other thing I forgot to mention is that the memory store does not share state, so if you have multiple servers, or even multiple node.js processes on a single server (with the [cluster](https://nodejs.org/api/cluster.html) module), you can end up with somewhat inconsistent blocking behavior due to that. (E.g. on a dual-core server, one process handles 6 requests and blocks the user, the other has only handled 3 requests and doesn't block them.)

In general, I think you should take one of two approaches:

* Use an external store to ensure users get consistent behavior regardless of what server or process they're connected to.
* Use the built-in memory store and not care that abusive users get inconsistent behavior

That said, I won't fight you on it - if you think your custom store is better for your situation, that's cool with me.
