### ISSUE TITLE
'Cannot set headers after they are sent to the client' when using onLimitReached function

### ISSUE THREAD

**Issue by samplics** [nfriedly/express-rate-limit#197]
```js
const apiRateLimit = expressRateLimit({
  windowMs: 300000, 
  max: 5, 
  onLimitReached: (req, res, options)=>{
    res.json({status:429, message: 'You are sending too many requests. Please try again later.'})
  }
})
```

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:543:11)
    at ServerResponse.header (/root/gamble/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/root/gamble/node_modules/express/lib/response.js:170:12)
    at Object.handler (/root/gamble/node_modules/express-rate-limit/lib/express-rate-limit.js:23:40)
    at /root/gamble/node_modules/express-rate-limit/lib/express-rate-limit.js:141:28
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by samplics** [comment]
dunno why it didnt keep my code formatting

**Comment by nfriedly** [comment]
I think you want to set that function for `handler` instead of `onLimitReached`. I kind of regret those names, but it would cause a lot of headaches for a lot of people if I changed them now.

* `handler` is for actually responding to a user, it is run for every request after a user has hit the limit.
* `onLimitReached` is for internal logging and whatnot; it is only run on the first time a user hits a limit. After it is run, `handler` is also run.

Also, I fixed up the formatting. One backtick is for "inline" things like a single word, three backticks is for a block, and thne three backtics + a language name enables syntax highlighting in the block. You can see some examples here: https://guides.github.com/features/mastering-markdown/#examples

**Comment by samplics** [comment]
> I think you want to set that function for `handler` instead of `onLimitReached`. I kind of regret those names, but it would cause a lot of headaches for a lot of people if I changed them now.
> 
> * `handler` is for actually responding to a user, it is run for every request after a user has hit the limit.
> * `onLimitReached` is for internal logging and whatnot; it is only run on the first time a user hits a limit. After it is run, `handler` is also run.
> 
> Also, I fixed up the formatting. One backtick is for "inline" things like a single word, three backticks is for a block, and three three backtics + a language name enables syntax highlighting in the block. You can see some examples here: https://guides.github.com/features/mastering-markdown/#examples

That worked! Thanks for the quick response.
