### ISSUE TITLE
Understanding the limitations of the default store  

### ISSUE THREAD

**Issue by oshihirii** [nfriedly/express-rate-limit#200]
Re:  https://github.com/nfriedly/express-rate-limit#stores   
> Memory Store (default, built-in) - stores hits in-memory in the Node.js process. Does not share state with other servers or processes.

Can someone please help me understand what this means and what its implications are?

Just to articulate my naivete more, I do not have an understanding of what node processes are, and cannot visualise how an app could be distributed across servers or how the concept of state relates to this subject.  

I am trying to implement this on an Node.js, MongoDB Atlas, Azure web app (Linux) which will be used by multiple people accessing the app.

Does each person's browser represent a node process when it is accessing the app?  And, if so, does this mean that the default store in `express-rate-limit` doesn't work if  more than one person accesses the app?

Apologies for my lack of knowledge.

**Comment by nfriedly** [comment]
> Can someone please help me understand what this means and what its implications are?

I believe that in your case, this won't matter. You can use the default built-in memory store and it will work just as you expect.

Node.js only uses one CPU core by default, but there are ways, such as with the [cluster](https://nodejs.org/api/cluster.html) module, to make it use all of the cores on a single server.  If your CPU has 4 cores, you'd probably start 4 processes to run on all 4 cores. Then you can deal with 4 incoming requests simultaneously. 

Say you set your max limit to 10 requests in express-rate-limit. The way the memory store works, it's 10 requests per process, so an end user could potentially get 40 requests in this case. But it's semi-random which process any request comes to, so they will see some rate-limit rejections in between 10 and 40 successful requests. After 40 successful requests, they will receive only rate-limit rejections. 

If you're just using express-rate-limit for abuse prevention and setting `headers: false`, then it doesn't really matter. They're guaranteed to get 10 successful requests, so they're getting what they bargained for, they just might get a little more if they're persistent.

If you're trying to make a public (or paid) API with explicit limits, and/or keeping `headers` enabled (it's enabled by default), then you probably want to use a different store once you have multiple servers or processes.

(The reason the headers matter is because with the MemoryStore, they'll tell you the limit for that specific process, so they'll be semi-random if you have multiple processes.)

All of the above holds true if you have multiple servers and a load balancer that forwards each incoming request to a random server, just change "process" to "server".

> Does each person's browser represent a node process when it is accessing the app? 

No, not for a Node.js server.

> And, if so, does this mean that the default store in express-rate-limit doesn't work if more than one person accesses the app?

Multiple people can access the app with the default store.
