### ISSUE TITLE
Warning: a promise was created in a handler but was not returned from it when used with Bluebird.

### ISSUE THREAD

**Issue by vpeshka** [nfriedly/express-rate-limit#202]
Hi,
I'm using your library in my API and I have met the warning regards to Promises. This warning produced by Bluebird, and more details that warning provided here: http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it. 

Warning happens every request while we not achieve limit. So probably it regards to Promise in options.store.incr callback.

Would it be fixed?

**Comment by nfriedly** [comment]
I think it's probably warning about these two:

https://github.com/nfriedly/express-rate-limit/blob/9309ceb602da6e16c6f3323b34f49d4e5b564aef/lib/express-rate-limit.js#L53

https://github.com/nfriedly/express-rate-limit/blob/9309ceb602da6e16c6f3323b34f49d4e5b564aef/lib/express-rate-limit.js#L71

Both of those are correct behavior and, IMO, bluebird shouldn't be warning about them. But, I don't think it would break anything to return them.

Do you want to test prefixing those lines with `return`  and see if it makes the bluebird warning go away and otherwise works correctly?

If you're not aware, testing against a local copy npm package can be fairly straightforward:

```sh
git clone https://github.com/nfriedly/express-rate-limit.git
cd express-rate-limit
npm ci
npm link
```
then, in your app, run

```sh
npm link express-rate-limit
```
That will cause it to use your local development copy of express-rate-limit instead of the copy downloaded from npm.

Make your changes and then restart your app to test the changes.

**Comment by vpeshka** [comment]
> I think it's probably warning about these two:
> 
> https://github.com/nfriedly/express-rate-limit/blob/9309ceb602da6e16c6f3323b34f49d4e5b564aef/lib/express-rate-limit.js#L53
> 
> https://github.com/nfriedly/express-rate-limit/blob/9309ceb602da6e16c6f3323b34f49d4e5b564aef/lib/express-rate-limit.js#L71
> 
> Both of those are correct behavior and, IMO, bluebird shouldn't be warning about them. But, I don't think it would break anything to return them.
> 
> Do you want to test prefixing those lines with `return` and see if it makes the bluebird warning go away and otherwise works correctly?
> 
> If you're not aware, testing against a local copy npm package can be fairly straightforward:
> 
> ```shell
> git clone https://github.com/nfriedly/express-rate-limit.git # (or fork it and use the url of your fork)
> cd express-rate-limit
> npm ci
> npm link
> ```
> 
> then, in your app, run
> 
> ```shell
> npm link express-rate-limit
> ```
> 
> That will cause it to use your local development copy of express-rate-limit instead of the copy downloaded from npm.
> 
> Make your changes and then restart your app to test the changes.

Hi @nfriedly,
Sorry for too long waiting time. I've tested few variant of fixes for that behaviour and only one of its has resolved the issue. After this 2 lines should be added: ``` return null; ``` (as it mentioned [here](http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it)).

https://github.com/nfriedly/express-rate-limit/blob/9309ceb602da6e16c6f3323b34f49d4e5b564aef/lib/express-rate-limit.js#L154

https://github.com/nfriedly/express-rate-limit/blob/9309ceb602da6e16c6f3323b34f49d4e5b564aef/lib/express-rate-limit.js#L157

For the first look the whole logic works in the same way as without this fix.

**Comment by nfriedly** [comment]
Oh, gee, now I owe you an apology for the delay. Somehow I missed your reply. Do you want to send me a PR with those two changes? I'd like to add a test also, but I'm not sure if that would be feasible.

**Comment by vpeshka** [comment]
@nfriedly [There is PR.](https://github.com/nfriedly/express-rate-limit/pull/222)
