### ISSUE TITLE
Inconsitent limits

### ISSUE THREAD

**Issue by orangejuicejones** [nfriedly/express-rate-limit#207]
Hi,
I'm running node + express with express-rate-limit for the first time with the below config.

```js
const limiter = rateLimit({
  windowMs: 1 * 60 * 1000, // 1 minute
  max: 5 // limit each IP to 100 requests per windowMs
});

ProductRoute.post('/data', limiter, cacheMiddleware(20), (req, res) => {
// return data
}
```

I understand that the user can make up to 5 calls in every minute. When I tested, I noticed I could make more than 5 requests in a minute if i make a request every 5 seconds. I also noticed if I make a call every second, I then get blocked on the 6th. 
I would have expected not more than 5 calls can be made in a minute irrespective.

**Comment by nfriedly** [comment]
Hi @orangejuicejones,

That's because the 1 minute doesn't start at the first request. The way the built-in memory store works is that all requests during a given minute get bucketed and then after the minute is elapsed, the bucket is emptied. So, in your 1 request every 5 seconds example, the bucket was emptied after you had made <=5 requests, resetting the counter to 0 and allowing you up to 5 requests for the next bucket.

With this setup, a user could get a burst of up to 10 requests if they timed it _just right_. But then they would have to wait a full minute to get 5 more requests, or two minutes to get another burst of 10. It's still 5/minute, it's just that the server's minute doesn't necessarily align to their clock.

This is a memory/load optimization that I felt was appropriate for the default store. However, if you want precise tracking, starting a per-user clock at exactly when the first request comes in, I believe all of the custom stores, as well as the other rate limiters mentioned in the readme offer this feature.
