### ISSUE TITLE
how to use resetAll

### ISSUE THREAD

**Issue by rever96** [nfriedly/express-rate-limit#208]
I've just imported express-rate-limit, implemented the basic following the npm usage without changing store.
It works really well, gj.
Now I want to add a function that clear the store for any emergency situations.
I've found there is an interface of resetAll that would be what i'm looking for, but I have no way to access it (am I wrong?).

In order to accomplish that task should I implement my own Store?

**Comment by nfriedly** [comment]
hi @rever96 

You're looking at this, right?

https://github.com/nfriedly/express-rate-limit/blob/b6318770e37b40e5345fb11d62e31acd6c5c76b1/lib/memory-store.js#L35-L38

That only exists on the MemoryStore, which is why it's not part of the official API; it's a leftover from before multiple stores were supported. You can technically use it, although I'm not sure I'd recommend it. Restarting the node.js process would have the same effect with the MemoryStore. What kind of emergency are you anticipating?

Nonetheless, if you do want to use it, you just need to create your own MemoryStore instance and make sure that both the limiter and the MemoryStore get the same `windowMs` value:

```js
const rateLimit = require("express-rate-limit");
const MemoryStore = require("express-rate-limit/lib/memory-store");

const windowMs = 15 * 60 * 1000; // 15 minutes

const store = new MemoryStore(windowMs);

const limiter = rateLimit({
  windowMs,
  store,
  max: 100 // limit each IP to 100 requests per windowMs
});

//  apply to all requests
app.use(limiter);

// later on...
store.resetAll();
```

I didn't test the above code, but it should at least give you the right idea.

**Comment by rever96** [comment]
yes, that's was what i was aiming for.
I limited my search on the limiter object.
Thx for the fast reply, I'll try to implement it asap.

"What kind of emergency are you anticipating?"
the ip blocked for a customer that need to login fast, from the admin panel should be a function to reset attemps without know the customer ip.

**Comment by nfriedly** [comment]
> the ip blocked for a customer that need to login fast, from the admin panel should be a function to reset attemps without know the customer ip.

Aah, I never thought of that. Glad I asked :) 

I need to do some revisions to the store API, maybe I'll make that a part of the 2.0 version. (Probably won't happen this year, though.)

Anyways, good luck with your project!
