### ISSUE TITLE
express-rate-limit handling double number of max value requests

### ISSUE THREAD

**Issue by shilpamahajan9** [nfriedly/express-rate-limit#212]
Hi,

I am using the library express-rate-limit to rate limit REST API to 5 request/second for a regular web server and followed the steps mentioned in https://www.npmjs.com/package/express-rate-limit/v/5.1.3

On localhost results are as expected i.e it handles 5 request/second but when deploy to testing server handles 10 requests/second i.e. double the value of max property, which is not expected.
Not sure why this is happening. What could be the possibilities that causes server to handle double the max value number of requests?

Thanks & Best regards,
Shilpa

**Comment by nfriedly** [comment]
Hi @shilpamahajan9 

Most likely, you have multiple servers or processes (e.g. with the `cluster` module). The default Memory Store keeps state in the process, so if the limit is 5 and there are two servers or processes, then an end user gets 5 requests to each.

Switching to any of the alternate stores will remedy this, although each requires some type of data store to synchronize everything.

**Comment by shilpamahajan9** [comment]
Thank you so much for your reply.
It was very helpful!

I have implemented the rate limiting but now struggling to test it. I tried below ways to test the rate limiting but not sure which one is correct as results are different for each of them. 

**Postman**: during windowMs, we are sending requests every 50 milliseconds. Results: 5 requests are successful and rest HTTP 429
**Shell script**: In the for loop sending number of requests for windowMs. This windowMs calculated like start of shell script execution + windowMs. Results: 12 to 15 requests are successful and rest HTTP 429.
**ab testing**: ab -t windowMs -c 50 -H "X-MyIO-Access: mykey" -H "X-MyIO-Account: myAccount" -H "Content-Type: application/json" -v 4 https://myurl/{id} Results: In the given windowMs, handling 20+ requests and rest HTTP 429

Not sure which test method is correct. Could you please suggest a best way to test our APIs rate limit. Any recommendation for tools. Your suggestions are welcome :)

Best regards,
Shilpa

**Comment by nfriedly** [comment]
How many server processes do you have running, and what store are you using?

The other thing I should mention is that on the default Memory Store, requests are bucketed to an internal clock. So if your limit is 5 per second, that second-timer doesn't start when the first request comes in, it starts when the server starts. 

If an end-user got the timing *just so*, they might manage to get 10 requests in a row because half go into one second and half go into the next. But they'd have to wait 2 seconds to be able to do that again. (It's an optimization to reduce the amount of memory and computation the Memory Store has to do.)

This module was initially built more for abuse-protection than for strictly enforcing API rate-limits, that's part of why the readme links to a few other rate-limiters that may be a better fit for scenarios such as that one.

I believe all of the third-party stores use a more precise tracking mechanism that keeps a per-user clock which starts on the first request from that user.

My advice is to not worry about it 🤷‍♂️ - but if that doesn't work for you, then you should probably use a different data store and/or a different library.

**Comment by shilpamahajan9** [comment]
Thanks for your prompt reply.

Any recommendation to test rate limit implemented for our APIs? Any tool to test?

Best regards,
Shilpa

**Comment by nfriedly** [comment]
I'd probably say to go with the postman one, but all of your suggestions seem reasonable.
