### ISSUE TITLE
handler should have access to options, just like onLimitReached

### ISSUE THREAD

**Issue by rubenstolk** [nfriedly/express-rate-limit#214]
`handler` should have access to `options`, just like `onLimitReached`

**Comment by nfriedly** [comment]
Hey, sorry this slipped through the cracks. I suppose that's a fair enough request, though.  It'd have to be a 4th param after `next`. Want to send a PR with the change and a test or two?

**Comment by rubenstolk** [comment]
Would love to, not sure if I'll find some time soon though...

**Comment by takeshirs** [comment]
Hey,
created a pull request for this:
https://github.com/nfriedly/express-rate-limit/pull/245

**Comment by nfriedly** [comment]
I believe this is possible without any changes. When the handler is called, the `this` value will point to `options`:

```js
rateLimit({
  windowMs: 60 * 60 * 1000, // 1 hour window
  max: 5, // start blocking after 5 requests
  handler: function(req, res, next) {
    const options = this;
    console.log(`max is ${options.max}`);
    res.status(options.statusCode).send(options.message);
  }
});
```

The main gotcha that you have to watch out for is that you can't use "fat arrow" (`() => {}`) functions, because they change the behavior of `this`.

**Comment by NoahAndrews** [comment]
The fact that you can access it that way feels like a side effect of an implementation detail. I think passing in the options object as a parameter is much more explicit and clear.

**Comment by nfriedly** [comment]
> feels like a side effect of an implementation detail.

That's true, it more or less is. 

But I really don't like adding a new param *after* the callback function. That just feels wrong. 

I also thought about trying to be clever and check if `options.handler.length >= 4` and then pass in `req, res, options, next` otherwise just `req, res, next`. That would do the right thing most of the time for most people.. but it'd be a nightmare to debug when it didn't. So I think that solution is out.

I'd also consider making a breaking API change and a major version release if I saw a lot of value in it... but, using `this` does work in the current codebase, and I'm willing to document and commit to keeping it working in future revisions. It's an awkward API, but I think it's the best option for the moment.

**Comment by takeshirs** [comment]
Hm, I can understand your concerns.
But regarding:

> But I really don't like adding a new param after the callback function. That just feels wrong.

It's just like it's done for the `handler` option, so I think it would be consistent to also add the `optionsUsed` parameter to `onLimitReached`.

**Comment by StephanBijzitter** [comment]
While `options` coming after `next` feels weird indeed, it would still be a non-breaking change.
With any new major release they could then be switched around to `options, req, res, next` which (in my opinion) feels more natural.

**Comment by nfriedly** [comment]
Alright, you guys have convinced me, I'll go ahead and merge in #245. I probably won't ever change the order, because backwards compatibility is more important IMO.
