### ISSUE TITLE
Limit each IP to 100 requests per windowMs

### ISSUE THREAD

**Issue by dattp** [nfriedly/express-rate-limit#216]
I'm understanding to limit the requests per IP address, but when I test with my application, it is limiting the requests to all IP addresses.

**Comment by NoahAndrews** [comment]
Is your server behind a proxy?

**Comment by burakkarakus** [comment]
My server is running on Azure App Service. iOS and Android apps call my server regularly to get data. Once one of the clients hit 429, my server responds to all requests with 429. Is that normal? I didn't understand from the readme that it was the case. Can you elaborate on that briefly?

**Comment by nfriedly** [comment]
@burakkarakus you're probably behind a proxy and are rate-limiting it's IP instead of your end-user's IPs,

Add this code to your app:

```js
// Enable if you're behind a reverse proxy (Heroku, Bluemix, AWS ELB, Nginx, etc)
// see https://expressjs.com/en/guide/behind-proxies.html
app.set('trust proxy', 1);
```

You may have to change the `1` to `2` or whatever if you're behind multiple proxies. `true` allows an unlimited number of proxies, but isn't recommended beyond your initial testing because a malicious end-user can pretend they're a proxy and then get essentially unlimited requests.

**Comment by burakkarakus** [comment]
As far as I can see, I am not _intentionally_ behind a proxy, but Azure App Service have many outbound IPs and I am _unintentionally_ blocking the users once one of the clients hit the limit. Thank you, I will try that.
