### ISSUE TITLE
Time or digits of windowMs for one month?

### ISSUE THREAD

**Issue by iamphoenix310** [nfriedly/express-rate-limit#223]
Hi, 

What would be the digits for the one-month duration? or 1-week duration? in windowMs? 

As I want to limit the requests on monthly basis. Kindly help.

**Comment by nfriedly** [comment]
Hi @iamphoenix310 

I would just do the math in code, so for a week:

```js
const limiter = rateLimit({
  windowMs: 7 * 24 * 60 * 60 * 1000, // 7 days
  max: 100 // limit each IP to 100 requests per windowMs
});
```

A month is trickier because months have different duration, but you could just go with 30 days to keep it simple.

A couple of important notes:
* The timer is not aligned to the beginning of the week/month. With the default memory store, the timer starts when the server boots up and just loops. With most of the other stores, it starts with the first request.
* With the default memory store, if you restart the node.js process it will reset the timer and the number of hits. 

I'm not sure this library is the best match for your use-case; you might want to look at some of the alternatives mentioned in the readme https://github.com/nfriedly/express-rate-limit#alternate-rate-limiters

**Comment by iamphoenix310** [comment]
Ok thanks. That is helpful.
