### ISSUE TITLE
not able to customize skip function

### ISSUE THREAD

**Issue by MallRoy** [nfriedly/express-rate-limit#229]
I need to intercept the response object and based on the status code and message. I will return true or false. But the skip function is first called with a status code of 200 and sends a response before I return the true or false value.
```      
skip: (req, res) => {
        return res.on('finish', function () {
          console.log(res.statusCode, res.body);
          if (
            res.statusCode === 400 &&
            res.body.error !== 'message'
          ) {
            return true;
          } else {
            return false;
          }
        });
    }
```

**Comment by nfriedly** [comment]
I think what you want is to set `skipFailedRequests: true` in your config, rather than setting a `skip` function.

The way the it works, skip has to be resolved to a true or false value *before* the request completes.  You could use an async function or a promise to make it wait, but if you did that waiting for the request to complete, then it would just hang until the request timed out, because it won't complete until after it gets an answer from `skip()`.

However, your code immediately returns the request (`res`), because that's what `res.on(...)` returns (for chaining). The `res` gets treated as `true` and causes all requests to be skipped. Then, after the request is finished, your callback is triggered and returns true or false, but nothing checks *that* return value.

**Comment by MallRoy** [comment]
skipFailedRequests will catch all the error. my requirement is to catch the specific error and increase the counter. Is there any other ways to achieve.?

**Comment by nfriedly** [comment]
Ah, I see. Perhaps you could call decrement directly on the store in that case? I'm just on my phone right now, but I can provide an example in an hour or two if you need.

**Comment by MallRoy** [comment]
Oh ok. If you provide some examples that will be really helpfull.

**Comment by nfriedly** [comment]
Ok, here you go:

```js
const rateLimit = require("express-rate-limit");
const MemoryStore =  require("express-rate-limit/lib/memory-store");

const windowMs = 5000; // or whatever

const store = new MemoryStore(windowMs);

const limiter = rateLimit({
  store,
  windowMs, // note: both the limiter and the store need the windowMs value
  // ...
});

//  apply to all requests
app.use(limiter);

// additional middleware that "un-counts" certain requests by modifying the store directly
app.use(function(req, res, next) {
  res.on('finish', function () {
    console.log(res.statusCode, res.body);
    if (
      res.statusCode === 400 &&
      res.body.error !== 'message'
    ) {
      store.decrement(req.ip) // or whatever you set `keyGenerator` to in the express-rate-limit config
    }
  });
  next();
});
```

I didn't test that, but hopefully it's close enough to get you the right idea even if it's not quite perfect

It should be about the same with an [alternate store](https://github.com/nfriedly/express-rate-limit#stores).

**Comment by MallRoy** [comment]
It's working!!!.. Thankyou @nfriedly
