### ISSUE TITLE
BUG:  in X-RateLimit-Reset divide date in 1000 instead of milliseconds difference 

### ISSUE THREAD

**Issue by ntedgi** [nfriedly/express-rate-limit#232]
following this repo memory store example 

[src link ](https://github.com/nfriedly/express-rate-limit/blob/master/lib/memory-store.js#L3)
```
function calculateNextResetTime(windowMs) {
  const d = new Date();
  d.setMilliseconds(d.getMilliseconds() + windowMs);
  return d;
}
```

then when we creating **X-RateLimit-Reset**
at : 

[src link](https://github.com/nfriedly/express-rate-limit/blob/master/lib/express-rate-limit.js#L83)

```
if (resetTime instanceof Date) {
     res.setHeader("Date", new Date().toUTCString());
     res.setHeader("X-RateLimit-Reset", Math.ceil(resetTime.getTime() / 1000));
}
```

for example, lets take  windowMs = (60 * 1000)

```
var d = new Date();
d.setMilliseconds(d.getMilliseconds() + 60*1000);
d.getTime()
//   1620105283120
new Date(1620105283120)
//   Tue May 04 2021 08:14:43 GMT+0300 (Israel Daylight Time)
new Date(Math.ceil(1620105726039 / 1000))

//   Mon Jan 19 1970 20:01:45 GMT+0200 (Israel Standard Time)

```
this response header  doesn't make sense
**RateLimit-Reset:1620105727** 

this is how the expected result should look 

<img width="883" alt="Screen Shot 2021-05-04 at 9 13 50" src="https://user-images.githubusercontent.com/31243793/116966550-19fefa80-acb9-11eb-8482-840697f36f91.png">

**Comment by nfriedly** [comment]
I'm a little confused here, which header are you saying is incorrect, `X-RateLimit-Reset` or `RateLimit-Reset`?

* `X-RateLimit-Reset` is set to a unix-style timestamp (number of seconds since January 1, 1970).
  * For example, `1620105727` is `Tue May 04 05:22:07 2021 UTC` ([source](https://duckduckgo.com/?q=unix+timestamp+1620105727&t=ffab&ia=answer))
  * I don't know that there is a formal definition for this header, but this is the way most APIs seem to use it, e.g. [twitter](https://developer.twitter.com/en/docs/twitter-api/rate-limits#headers-and-codes), [github](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting)
* `RateLimit-Reset` is set to a delta-seconds value (how many seconds until the ratelimit resets) ([source](https://tools.ietf.org/id/draft-polli-ratelimit-headers-00.html#rfc.section.3.3))
  * For example, `51` would mean 51 seconds from _right now_, which would mean `Tue May 04 15:08:16 2021 UTC` as I'm writing this.

The first one should be a really big number, the second one should be a small number.

I suspect some confusion may be coming from how JavaScript handles dates - JavaScript works in milliseconds since January 1, 1970, so the numbers are 1000x larger.

Also, from your last code block, this line looks incorrect:
```js
new Date(Math.ceil(1620105726039 / 1000))
```
It should probably be
```js
new Date(1620105726039)
```
