### ISSUE TITLE
Question: Best way to manage errors returned from the store

### ISSUE THREAD

**Issue by kargakis** [nfriedly/express-rate-limit#247]
What is the best way to manage [this error](https://github.com/nfriedly/express-rate-limit/blob/c4f9c46ddf6d6f86861007df431d775deb5f379c/lib/express-rate-limit.js#L67)? Do I need an additional handler on my http server right after the ratelimiter to handle it I guess? There is a certain error returned by Redis that we want to avoid failing on, ie as if we run next() instead of next(err) from the ratelimiter.

**Comment by nfriedly** [comment]
Hum.. that's an interesting question. Yea, I suppose you could just wrap it to ignore errors, so instead of `app.use(limiter)`, do something like this:

```js
function noErrorLimiter(req, res, next) {
  limiter(req, res, () => next());
}
app.use(noErrorLimiter);
```

That will throw away *all* errors, so you may want to add some additional logic to check for your one particular error and throw it away, but resurface any other errors. Up to you.
