### ISSUE TITLE
Expose `MemoryStore` as a named export

### ISSUE THREAD

**Issue by peterbe** [nfriedly/express-rate-limit#289]
### Description

I want to be able to toggle between using a custom third-party store and the "default" memory one. 
Based on https://github.com/nfriedly/express-rate-limit#store you can write your own. I don't want to do that. I want to use the in-memory "default" one from this package. 
E.g. 
```js
export default rateLimit({
   ...
  store: REDIS_URL
    ? new RedisStore(REDIS_STUFF)
    : new Memory(),
})

```
You can't do
```js
import rateLimit, {MemoryStore} from 'express-rate-limit'
```
because the only thing exported is the `rateLimit` default function. 

My only way to do this now is to copy-n-paste the source code from https://github.com/nfriedly/express-rate-limit/blob/master/source/memory-store.ts into my project. 

### Why

To avoid the copy-n-paste and then have to rewrite it if the API changes. 

### Alternatives

Mentioned above .

**Comment by peterbe** [comment]
Sorry if I'm confused, but I think the `Store` class is exported in the TypeScript but it's just not exported in the `dist/index.mjs` JS code.

**Comment by peterbe** [comment]
Hmm... I think I realize my mistake now. 
If you do this:
```js
export default rateLimit({
   ...
  store: REDIS_URL
    ? new RedisStore(REDIS_STUFF)
    : undefined,
})
```
it thinks that the store I want is `undefined` which doesn't have a `.incr` so it throws because `undefined` is not a valid store. 

I solved this by refactoring how I use the constructor. This works:

```js
const options = {
   ...
}
if (REDIS_URL) {
  options.store = new RedisStore(REDIS_STUFF)
}
export default rateLimit(options)
```
Now, I get the lovely default in-memory store if I don't specifically set that 3rd party `RedisStore`. 
Somewhere in the code, it does something like this:
```js
// Somewhere in the constructor
this.store = new MemoryStore()   // the default
...
if ('store' in options) {
  this.store = options.store
}
```
when, I speculate, it should be something like this instead:
```js
if (options.store) {
  this.store = options.store 
}
```

**Comment by nfriedly** [comment]
Yea, we do some "fancy footwork" with the `store` option in order to support both the legacy API and the modern API and do some runtime type-checking *AND* have a fallback to the default memory store. There's probably room for improvement, but it seems to mostly work.

As for exporting the MemoryStore, yea, that seems like a good idea. Would you like to send in a PR?

**Comment by gamemaker1** [comment]
Hi,

Thanks for opening this issue!

As you have noted, the memory store is exported only internally (from `source/memory-store.ts`, and imported in `source/lib.ts`) but not to the world. This could be done easily (just adding one line `export { default as MemoryStore } from './memory-store.js'` to `source/index.ts`).

> https://github.com/nfriedly/express-rate-limit/issues/289#issuecomment-1015767036 > Somewhere in the code, it does something like this:

We actually use the following (https://github.com/nfriedly/express-rate-limit/blob/master/source/lib.ts#L94-L131):

```ts
const options = {
	windowMs: 60_000,
	max: 5,
	// ... etc - defaults for all the options
	...passedOptions, // So whatever is passed in the options overrides the defaults
}
```

I'm surprised that setting `store` to `undefined` overrides the default value instead of keeping it as is. Mabye `null` works instead?

Anyways, I believe the `MemoryStore` export will be more helpful here. @nfriedly what do you think?

**Comment by gamemaker1** [comment]
Hahah @nfriedly beat me by a minute XD

**Comment by peterbe** [comment]
I think this issue became about two different things:

1. Settings `store: undefined` should mean the same as not setting it at all. I.e. `store: undefined` should automatically fallback to the built-in in-memory one. 
2. If, for some reason, someone needs to import the built-in default in-memory store class, it should be possible with `import {MemoryStore} from 'express-rate-limit'`

**Comment by gamemaker1** [comment]
Yes, I agree.

For (1), I'll try to find out a way that sets the default value if the option is set to `undefined`.

For (2), feel free to open a PR, or I could do it too :D
