### ISSUE TITLE
CommonJS Store Example

### ISSUE THREAD

**Issue by jakowenko** [nfriedly/express-rate-limit#291]
### Description

I'm not super familiar with TypeScript, but I do have a need for writing a custom store to interface with a DynamoDB Table.

I followed the example from the [custom store section](https://www.npmjs.com/package/express-rate-limit#store) and attempted to write it in CommonJS, but it doesn't seem like all the functions are behaving as I would expect.

### Why

Some projects are all in CommonJS and having a way to write a custom store would be helpful, maybe it's already possible and I'm just missing something.

### Alternatives

I attempted to write a custom store with the main code looking like the below.

```javascript
class DynamoStore {
  constructor(customParam) {
    this.customParam = customParam;
  }

  init(options) {
    this.windowMs = options.windowMs;
  }

  async increment(key) {
    return {
      totalHits,
      resetTime,
    };
  }

  async decrement(key) {}

  async resetKey(key) {}

  async resetAll() {}
}
module.exports = DynamoStore;
```

I did verify the `increment` function is called when the API is hit, but returning the data doesn't seem to callback anything and the API just responds with `{}`, it doesn't seem to jump to the next middleware function.

**Comment by briananstett** [comment]
I too am having this problem. Looking forward to getting some guidance.

**Comment by gamemaker1** [comment]
Hi @jakowenko,

The example that you have written in your OP should work. Here is another example in case it helps (the `MemoryStore` written in Javascript):

```js
// source/memory-store.js
// Memory store written in CJS Javascript

class MemoryStore {
	hits = {}

	async increment(key) {
		if (!this.hits[key]) this.hits[key] = 0
		this.hits[key] += 1

		return {
			totalHits: this.hits[key],
			resetTime: undefined,
		}
	}

	async decrement(key) {
		if (this.hits[key]) this.hits[key]--
	}

	async resetKey(key) {
		delete this.hits[key]
	}
}

module.exports = MemoryStore
```

> Returning the data doesn't seem to callback anything

The `increment` function returns a `Promise`, which is `await`-ed [here](https://github.com/nfriedly/express-rate-limit/blob/master/source/lib.ts#L213) and the `totalHits` and `resetTime` are used to calculate whether the client has exceeded the rate limit and send the headers. There isn't any callback involved unless you use the Legacy store format.

> The API just responds with {}, it doesn't seem to jump to the next middleware function

This usually happens when an async error is thrown by a middleware and it is not handled by a try-catch block or error handler. You could add an error handler by following [this guide in the Express docs](https://expressjs.com/en/guide/error-handling.html).

I'm sorry but I can't help you further without seeing the complete code 😅

**Comment by gamemaker1** [comment]
@briananstett Could you please open a new issue using the bug report template with an example of what you are trying to do? That will enable us to help you sort out the problem.

**Comment by nfriedly** [comment]
I went ahead and added a JavaScript example to the wiki to accompany the TypeScript example: https://github.com/nfriedly/express-rate-limit/wiki/Creating-Your-Own-Store#javascript--commonjs
