### ISSUE TITLE
keyGenerator

### ISSUE THREAD

**Issue by mihirchronicles** [nfriedly/express-rate-limit#41]
In your docs you mentioned, a default for keyGenerator is req.ip. But what are my other options? I would like to set it to a counter instead of an ipAdress. Is that possible? Thanks!

**Comment by nfriedly** [comment]
It's a function, so you can provide anything you want. It's passed in the [Request](http://expressjs.com/en/4x/api.html#req) and [Response](http://expressjs.com/en/4x/api.html#res) objects, and it must execute synchronously and return some value.

You could make a counter like so:

```js
var RateLimit = require('express-rate-limit');

var counter = 0;

var limiter = new RateLimit({
  // ...
  keyGenerator: function(req, res) {
    counter++;
    return counter;
  });
});

app.use(limiter);
```

However, that example wouldn't actually make sense, because every request would get a new key and thus nothing would reach the rate-limit.

Internally, there's [already a counter object](https://github.com/nfriedly/express-rate-limit/blob/master/lib/memory-store.js). It takes the key returned by the `keyGenerator` function, and increments the value associated with that key. Then it compares the value to the configured limit to decide whether to allow or deny the request.

I'd encourage you to read through the source code of the library to get a better understanding and help decide if it will meet your needs.

**Comment by mihirchronicles** [comment]
Okay thank you so much! Another solution I was looking at-- can I also hard set my req.ip == to 127.0.0.1 so it will only track my local even if it is being hit by different ip address?

**Comment by mihirchronicles** [comment]
And do you have any suggestions on error handling?
