### ISSUE TITLE
if I start my project in cluster mode

### ISSUE THREAD

**Issue by liuwensa** [nfriedly/express-rate-limit#51]
if I start my project in cluster mode, is it work?

it base on the global hits

**Comment by nfriedly** [comment]
If you use the [redis plugin](https://npmjs.org/package/rate-limit-redis), then yes, it will work as expected.

If you use it in cluster mode with the default memory-store, it will work in an "eventually consistent" sort of way - instead of a single global limit, each IP gets a per-worker limit. A non-abusive user will never hit this limit, and an abusive user will eventually hit the limit on all workers. There will be some in-between time where some workers block the abusive user and others do not, this may or may not be a big concern depending on the situation.

You could also use [sticky-session](https://github.com/indutny/sticky-session) with the cluster module to guarantee that a given IP is always routed to the same worker. That will prevent the in-between time, as long as you only have a single server. (Or, if you have a load-balancer that also offers sticky sessions, then it could scale to multiple servers.)
