### ISSUE TITLE
Query: After how much time a user is allowed to hit the API again after being rate limited?

### ISSUE THREAD

**Issue by puneetmakkar** [nfriedly/express-rate-limit#56]
After how much time a user is allowed to hit the API again after being rate limited?

**Comment by nfriedly** [comment]
It varies between 0 and your `windowMs` setting. The default `windowMs` is 60000, which translates to 1 minute.

What makes this module efficient is that all requests are grouped into "buckets" - If your window is 30 minutes, and you start the server at 12:00, then all requests between 12:00 and 12:30 go into the same bucket. Once a user is blocked, they remain blocked until the end of the window. 

So, if they get blocked at 12:01, then they are blocked for the next 29 minutes. If they get blocked at 12:29, then they are only blocked for 1 minute.

This works in general, because while an abusive user might be happen to get 2x the limit from 12:29-12:31, they will then be blocked until 1:00. 

But the down side is less precision in the blocks it enforces. If you need something more precise, then there are other modules available, although they all have more overhead in order to add that precision.

**Comment by robertour** [comment]
Is it possible to block the user for longer?

**Comment by nfriedly** [comment]
No, not at the moment. The block length has to be the same as the window length.

**Comment by robertour** [comment]
Thanks nfriedly, I found [this other issue](https://github.com/nfriedly/express-rate-limit/issues/77), and use that to create a solution: https://stackoverflow.com/questions/61563026/how-to-increase-the-blocking-time-period-after-being-rate-limited-using-express/61563027#61563027.

Cheers!
