### ISSUE TITLE
What about IP spoofing?

### ISSUE THREAD

**Issue by Stellaverse** [nfriedly/express-rate-limit#6]
Hey Nathan,

A very nice module you've created. Thanks a tonne for this.

I have a question about IP spoofing. I realize it's quite difficult to spoof your IP these days, and it would be a niche attack vector to consider, but do you have any knowledge or ideas about how IP spoofing could circumvent this module?

**Comment by nfriedly** [comment]
Yea, there's a couple of vectors there:

* If the attacker knows a third party's IP, they can use spoofing to make the server deny service to that third party.
* If the attacker doesn't need the servers response to carry out the attack, then IP spoofing will effectively bypass this module.

For something like a login or password reset form, you could mitigate the second attack vector by putting a CSRF token in the form and rate-limitijg that.

Old

**Comment by nfriedly** [comment]
Sorry. typing this on a phone...

Old versions of the library had a `global: true` option, which would basically lock it down for everyone if an attacker hit the site too hard with spoofed IPs, but it wasn't that useful in practice and got removed from v2.

**Comment by Stellaverse** [comment]
Aces. Thanks for the quick, helpful reply.

**Comment by kevinwheeler** [comment]
I apologize, I don't understand the bit about a CSRF token and rate limiting that. What would the attacker be trying to accomplish with a login form if he doesn't need the response? Certainly not logging in/cracking the password since he won't have the response. Also, what value does the CSRF token provide other than its standard use of making sure a user doesn't unintentionally submit a form?
