### ISSUE TITLE
Allow passing custom json to `message`.

### ISSUE THREAD

**Issue by SimonSchick** [nfriedly/express-rate-limit#63]
Our API has it's own error format and I'd rather not have it dictated by a library and overriding `handler` entirely seems a little redundant as it forces me to re-implement the `headers`, `statusCode` and `message` behaviour.

Ideally you would check if `options.message` is an object and respond with it directly.

**Comment by nfriedly** [comment]
Yea, I think the default handler needs to be a bit dumber so that it just does `res.send(options.message)` without the `res.format` nonsense. That way, if you set it to an object, it'll get returned as JSON, if you set it to a string, it'll get returned as html. 

But that's a breaking change, so it won't go out in a minor version, and I feel like this lib is in need of a major revamp for the next major version.

**Comment by nfriedly** [comment]
This is now done in v3.0.0
