### ISSUE TITLE
Why is a store responsible for resetting counts?

### ISSUE THREAD

**Issue by eyelidlessness** [nfriedly/express-rate-limit#76]
I've implemented a custom (Postgres) store, but missed the fact that the store is apparently responsible for resetting counts. Why is it implemented this way? It seems to me that the store should provide an interface to reset counts, but that the core library should be responsible for calling that interface.

At a minimum, it would be nice if this requirement were documented. As it is, my implementation would eventually leave all users rate limited permanently.

**Comment by nfriedly** [comment]
\>_< 

Yea, sorry, that's painful.

The reason it's done this way is for efficiency. The existing store's use different methods of purging data, with the memory one nuking everything on a setTimeout interval, and the redis one using redis's built-in expiration feature. 

Also, I never really intended for this thing to be extensible, it just kind of happened :/

I don't think postgres has anything like redis's automatic expiration, but you can fake it pretty well with timestamps + an optional background job (setInterval, or cron, or whatever) that goes in and deletes older things occasionally.

If you record each hit individually, you could do a `SELECT COUNT(*) FROM hits_table WHERE timestamp < NOW() - interval '1 hour'` -  that will give you the number of hits less than an hour old and ignore anything older. 

Or, if you are just adding a single row per user/IP/whatever, you can add a list_seen column and, if the timestamp is more than the limit, reset it and the hits, but if it's less than the limit then just increment the hits. Make sure you do the increment in your SQL, not in Node.js, though. (Something like `UPDATE TABLE hits_table SET hits_count = hits_count + 1 WHERE ip = '<ip>'`, or similar.) Otherwise a malicious actor can exploit the time between reading and writing to get way more hits than they should.

Or use [express-brute](https://www.npmjs.com/package/express-brute) with the [Knex.js store](https://github.com/llambda/brute-knex). Honestly, that's probably your best option.

**Comment by eyelidlessness** [comment]
@nfriedly thanks for your quick reply.

> The reason it's done this way is for efficiency. The existing store's use different methods of purging data, with the memory one nuking everything on a setTimeout interval, and the redis one using redis's built-in expiration feature to delete each user's records individually.

This makes sense, it's something I hadn't really considered. It seems to me the best way to address this is to have the core lib call the store's `resetAll` method on an interval, and have a store like Redis simply ignore that call.

> Also, I never really intended for this thing to be extensible, it just kind of happened :/

That's fair. I would be happy to take a bit of time to submit a PR making the change I suggested above (or something else if you'd prefer).

> Make sure you do the increment in your SQL, not in Node.js, though. (Something like UPDATE TABLE hits_table SET hits_count = hits_count + 1 WHERE ip = '<ip>', or similar.) Otherwise a malicious actor can exploit the time between reading and writing to get way more hits than they should.
> 
> Or use express-brute with the Knex.js store. Honestly, that's probably your best option.

The former is exactly why I don't use the latter. (See https://github.com/AdamPflug/express-brute/issues/46)

**Comment by nfriedly** [comment]
Doh, there goes my easy answer :/

I like the resetAll idea, although what happens when there are multiple servers / processes?

Also, it shouldn't set up the interval if the store doesn't have a resetAll method, but that's easy enough. It's the first thing that I'm unsure about.

**Comment by eyelidlessness** [comment]
@nfriedly That's a fair point, and one I hadn't considered. There are a multitude of different ways that node can be run in multiple processes, which makes it all the more complicated. I think with that in mind it might be the current approach is the best one, as the semantics for resetting counts will differ significantly between different stores.

Thanks again for your responsiveness on this and for explaining your considerations behind the current design.

**Comment by aymericbouzy** [comment]
Thanks for the explanation. Could we include this in the documentation ? I've had the same issue.
