### ISSUE TITLE
Clearing all the storage while using Key Generator with custom value.

### ISSUE THREAD

**Issue by kalyantolety** [nfriedly/express-rate-limit#93]
I have found this after extensive testing. If I try logging from two different IP's and one of them reached the limit. Now I use second IP after some time  and complete the limit for that too. Now if the first ones blocking time is completed and it clears the storage, it will also clear the records for the second IP which still has some time to regain access as well!!

**Comment by nfriedly** [comment]
Yes, that is the way that the MemoryStore is implemented, because it allows this module to be much more light-weight.  In practice, I've found that this is good enough for most use-cases.

If you need something more precise, try out the Redis or Memcached stores, or switch to version 1.x where every IP got it's own time window.
