### ISSUE TITLE
Retry-After header always default with memory store

### ISSUE THREAD

**Issue by JarrodAMcEvers** [nfriedly/express-rate-limit#96]
I noticed that if you do not have windowMs set while you are using a store that has an expiration, the Retry-After header will always be whatever the default for windowMs is.

I looked into RedisStore and it does not look like you could retrieve expiry from it in the case that windowMs is not set.

This is the code I had when I noticed this.
```
var limiter = new RateLimit({
  store: new RedisStore({
    expiry: 100,
    client: redisClient
  }),
  max: 100,
  delayMs: 0
});
app.use(limiter);
```

**Comment by JarrodAMcEvers** [comment]
Here was a way I got around the windowMs issue;
```
var limiter = new RateLimit({
  store: new RedisStore({
    expiry: 100,
    client: redisClient
  }),
  max: 100,
  delayMs: 0,
  handler: function (req, res) {
    res.set('Retry-After', 100);
    res.status(429).json({ message: 'Too many requests' });
  }
});
app.use(limiter);
```
Set the Retry-After header in the handler.

**Comment by JarrodAMcEvers** [comment]
That's what I did initially to fix the problem. Just seems odd to specify the expiration twice; once in the store you use and the windowMs field.

Having the remaining amount seems like the best way to go.

**Comment by Martii** [comment]
@nfriedly 

> I have a goal of updating the stores to tell express-rate-limit how much time is remaining

:+1: 

So I've got a related conundrum. We have someone hitting the limit and continues to ignore the `Retry-After` yet after the "fixed" expiration time both in the Memory Store and the Mongo Store those records expire at the end of the designated period e.g. we sync those currently to the same period.

Is there a way to "`touch` plus period"  the expiration date so it's "slides" to the same initial... ex. set to 1 hour... someone hits the route again... shift to a full hour again instead of period minus time elapsed. Current behavior says after 1 hour let 'em back in for another DoS attempt which wasn't pleasant to discover. :\

**Comment by nfriedly** [comment]
Hum.. I don't think that's possible with the current design. Let me think about it a bit more.

**Comment by Martii** [comment]
@nfriedly 

It appears that the Mongo Store does this with `resetExpireDateOnChange` and appears to work *(still running some long term tests where I can't easily test this without affecting everyone... and annoying them with the testing ;)*... it turns the expiration date in the DB to a "rolling" expiration date if they continue.

However the Memory Store for sure resets after the fixed period thus letting them back in to do their evil deed again.

**Comment by nfriedly** [comment]
Cool!  If you want to look into extending the mongo store to add the touch capability, you should talk to @2do2go about that.

I'm still thinking about how it could be don in the memory store without using a lot of resources. Perhaps a "double window" mode where a user that is banned in the current window and makes a subsequent request will also be pre-banned in the next window. So they have to wait a full window's worth of time without any requests to get un-banned.
